({
    desc: "Go over these questions to deepen your understanding",
    questions: [
        `In this workshop, the english word path is used with two completely different meanings. What are the two meanings of path?`,
        `How many endpoints are in the server?`,
        `What is the name attribute of our file input element? Was it arbitrarily chosen? Where else do we refer to it?`,
        `How do we indicate that an endpoint will receive an HTTP request generated by a form with a file in it?`,
        `Are the filenames genereated by multer random? Do they have an extension?`,
        `Why do we have to rename the files? What would happen if you didn't?`,
        `Where do we indicate to multer into which directory the files should be placed?`
    ]
})